# This file was generated by GoReleaser. DO NOT EDIT.
cask "lazyslice" do
  version "0.2.0"

  on_macos do
    on_arm do
      sha256 "df5e68932121571ca860e4161eb7a7631315be31d7fdb866981b727e4e3f5b01"
      url "https://github.com/Liarea/lazyslice/releases/download/v#{version}/lazyslice_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "4d461ee59c4ef74e9782a5f422a3b4fc94b126f30c8362a77d366bbcd6cdaf43"
      url "https://github.com/Liarea/lazyslice/releases/download/v#{version}/lazyslice_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "3d09f54f1f5b7b45a20188720baf2353dfae3be6d6e0884d796cc186d7c5c97c"
      url "https://github.com/Liarea/lazyslice/releases/download/v#{version}/lazyslice_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "cb8a65e9af246e4e9ec2619c49f4d2b640fb82dc29d80195c049766f4e9bf584"
      url "https://github.com/Liarea/lazyslice/releases/download/v#{version}/lazyslice_#{version}_linux_amd64.tar.gz"
    end
  end

  name "lazyslice"
  desc "Snapshot a production SQL database into a safe local copy"
  homepage "https://github.com/Liarea/lazyslice"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "lazyslice"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/lazyslice"]
    end
  end

  # No zap stanza required
end
