# This file was generated by GoReleaser. DO NOT EDIT.
cask "lazyslice" do
  version "0.0.3"

  on_macos do
    on_arm do
      sha256 "3bb3f24d3d4768e3a7f1573f7deb1f2392cb563056a8d0467ee9940ff3cdfd3d"
      url "https://github.com/Liarea/lazyslice/releases/download/v#{version}/lazyslice_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "ac5d362807bf454f6132367152772e0d8676414725cbaa79e4a7c7b7e7b7a582"
      url "https://github.com/Liarea/lazyslice/releases/download/v#{version}/lazyslice_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "525f1d371913b989c09f3aee01d905149c34937cec870614613287fc9d7ff0a0"
      url "https://github.com/Liarea/lazyslice/releases/download/v#{version}/lazyslice_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "ddc4142b9daab3d37fdcf86f33f96029ad5249ef6172e694d9f44a41416bfe90"
      url "https://github.com/Liarea/lazyslice/releases/download/v#{version}/lazyslice_#{version}_linux_amd64.tar.gz"
    end
  end

  name "lazyslice"
  desc "Snapshot a production SQL database into a safe local copy"
  homepage "https://github.com/Liarea/lazyslice"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "lazyslice"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/lazyslice"]
    end
  end

  # No zap stanza required
end
