# This file was generated by GoReleaser. DO NOT EDIT.
cask "lazyslice" do
  version "0.1.0"

  on_macos do
    on_arm do
      sha256 "abb397f6d1235e669c28acd30b8eb77956ebb888a97e19b995e2183733129b58"
      url "https://github.com/Liarea/lazyslice/releases/download/v#{version}/lazyslice_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "2500dfb456bc2eee10d9987554cfa9def65d14c5c0bd95a483aba340434f7820"
      url "https://github.com/Liarea/lazyslice/releases/download/v#{version}/lazyslice_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "9d882487c1278912c4645a8efd3f2dc9b616730cec37fe850e27d5b3e13eb041"
      url "https://github.com/Liarea/lazyslice/releases/download/v#{version}/lazyslice_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "fd7882913409d8f4f521be4c1caeffd96030f6763640f62e2775173f65670bb7"
      url "https://github.com/Liarea/lazyslice/releases/download/v#{version}/lazyslice_#{version}_linux_amd64.tar.gz"
    end
  end

  name "lazyslice"
  desc "Snapshot a production SQL database into a safe local copy"
  homepage "https://github.com/Liarea/lazyslice"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "lazyslice"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/lazyslice"]
    end
  end

  # No zap stanza required
end
